### ISSUE TITLE
Publish latest changes?

### ISSUE THREAD

**Issue by sveisvei** [gigara/rush-github-action-build-cache-plugin#3]

**Comment by gigara** [comment]
which changes?

**Comment by sveisvei** [comment]
https://github.com/gigara/rush-github-action-build-cache-plugin/pull/2

**Comment by sveisvei** [comment]
The changes you merged in #2 has not been released on npm. No "rush", I use my own version.

**Comment by gigara** [comment]
@sveisvei I published the latest changes with 7e5fbb9. Thanks for your contribution.
